name: Build EndlessEnchantRemastered

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run maven build lifecycle
        run: mvn --batch-mode clean test package

      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project
        
      - name: Upload plugin file
        uses: actions/upload-artifact@v2
        with:
          name: ProtocolLib
          path: target/EndlessEnchant-${{ steps.project.outputs.version }}.jar
